// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
    name,
    description,
    employee_count,
    registered,
    company_type,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, description, employee_count, registered, company_type, created_at, updated_at, created_by, updated_by
`

type CreateCompanyParams struct {
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	EmployeeCount int32       `json:"employee_count"`
	Registered    bool        `json:"registered"`
	CompanyType   string      `json:"company_type"`
	CreatedBy     pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Description,
		arg.EmployeeCount,
		arg.Registered,
		arg.CompanyType,
		arg.CreatedBy,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EmployeeCount,
		&i.Registered,
		&i.CompanyType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies
WHERE ID = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, description, employee_count, registered, company_type, created_at, updated_at, created_by, updated_by
FROM companies
WHERE ID = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EmployeeCount,
		&i.Registered,
		&i.CompanyType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getCompanyByName = `-- name: GetCompanyByName :one
SELECT id, name, description, employee_count, registered, company_type, created_at, updated_at, created_by, updated_by
FROM companies
WHERE name = $1
`

func (q *Queries) GetCompanyByName(ctx context.Context, name string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByName, name)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EmployeeCount,
		&i.Registered,
		&i.CompanyType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    employee_count = COALESCE($3, employee_count),
    registered = COALESCE($4, registered),
    company_type = COALESCE($5, company_type),
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $6
WHERE ID = $7
RETURNING id, name, description, employee_count, registered, company_type, created_at, updated_at, created_by, updated_by
`

type UpdateCompanyParams struct {
	Name          pgtype.Text `json:"name"`
	Description   pgtype.Text `json:"description"`
	EmployeeCount pgtype.Int4 `json:"employee_count"`
	Registered    pgtype.Bool `json:"registered"`
	CompanyType   pgtype.Text `json:"company_type"`
	UpdatedBy     pgtype.UUID `json:"updated_by"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.Description,
		arg.EmployeeCount,
		arg.Registered,
		arg.CompanyType,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EmployeeCount,
		&i.Registered,
		&i.CompanyType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
