// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID            uuid.UUID        `json:"id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	EmployeeCount int32            `json:"employee_count"`
	Registered    bool             `json:"registered"`
	CompanyType   string           `json:"company_type"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CreatedBy     pgtype.UUID      `json:"created_by"`
	UpdatedBy     pgtype.UUID      `json:"updated_by"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	LastLogin    pgtype.Timestamp `json:"last_login"`
}
